# Generated by Django

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PitchTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("template_content", models.TextField()),
                (
                    "industry",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "pitch_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("refined", "Refined"),
                            ("final", "Final"),
                            ("ab_variant", "A/B Variant"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of template variables",
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="Pitch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "pitch_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("refined", "Refined"),
                            ("final", "Final"),
                            ("ab_variant", "A/B Variant"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("scored", "Scored"),
                            ("refined", "Refined"),
                            ("approved", "Approved"),
                            ("sent", "Sent"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Aggregated scores from pitch scoring",
                    ),
                ),
                ("feedback", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "generated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agent or user that generated this pitch",
                        max_length=100,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("friendly", "Friendly"),
                            ("urgent", "Urgent"),
                            ("consultative", "Consultative"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=10),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitches",
                        to="customers.customer",
                    ),
                ),
                (
                    "parent_pitch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="pitches.pitch",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pitches",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PitchScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "dimension",
                    models.CharField(
                        help_text="Scoring dimension name",
                        max_length=50,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        help_text="Score from 0.0 to 1.0",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "scored_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agent or user that provided this score",
                        max_length=100,
                    ),
                ),
                (
                    "pitch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pitch_scores",
                        to="pitches.pitch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("pitch", "dimension", "scored_by")},
            },
        ),
    ]
