# Generated by Django

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pitches", "0001_initial"),
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PitchAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("shares_count", models.IntegerField(default=0)),
                (
                    "open_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Email open rate percentage",
                    ),
                ),
                (
                    "response_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Response rate percentage",
                    ),
                ),
                ("conversion", models.BooleanField(default=False)),
                (
                    "time_to_response",
                    models.DurationField(
                        blank=True,
                        help_text="Time from pitch sent to first response",
                        null=True,
                    ),
                ),
                (
                    "a_b_test_group",
                    models.CharField(
                        blank=True,
                        help_text="A/B test group identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "pitch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="pitches.pitch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "Counter"),
                            ("gauge", "Gauge"),
                            ("percentage", "Percentage"),
                            ("trend", "Trend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField(default=0.0)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict),
                ),
            ],
            options={
                "ordering": ["-date", "name"],
                "unique_together": {("name", "period", "date")},
            },
        ),
        migrations.CreateModel(
            name="AgentPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "total_executions",
                    models.IntegerField(default=0),
                ),
                (
                    "successful_executions",
                    models.IntegerField(default=0),
                ),
                ("avg_tokens", models.IntegerField(default=0)),
                (
                    "avg_duration",
                    models.FloatField(
                        default=0.0,
                        help_text="Average execution duration in seconds",
                    ),
                ),
                (
                    "avg_quality_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Average quality score from 0.0 to 1.0",
                    ),
                ),
                (
                    "agent_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="agents.agentconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("agent_config", "period", "date")},
            },
        ),
    ]
