# Generated by Django

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                (
                    "industry",
                    models.CharField(db_index=True, max_length=100),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("startup", "Startup"),
                            ("smb", "Small & Medium Business"),
                            ("mid-market", "Mid-Market"),
                            ("enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        default="smb",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("website", models.URLField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "preferences",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "interaction_history",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "customer_360_data",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of string tags",
                    ),
                ),
                (
                    "lead_score",
                    models.IntegerField(
                        default=0,
                        help_text="Lead score from 0 to 100",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("lead", "Lead"),
                            ("qualified", "Qualified"),
                            ("customer", "Customer"),
                            ("churned", "Churned"),
                        ],
                        db_index=True,
                        default="prospect",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("call", "Call"),
                            ("meeting", "Meeting"),
                            ("demo", "Demo"),
                            ("pitch", "Pitch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "sentiment_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Sentiment score from -1.0 to 1.0",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
