# Generated by Django

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("social", "Social"),
                            ("multi-channel", "Multi-Channel"),
                            ("abtest", "A/B Test"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "target_industry",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "target_company_size",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("goals", models.JSONField(blank=True, default=dict)),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, default=0.00, max_digits=12
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Campaign performance metrics",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("pitched", "Pitched"),
                            ("responded", "Responded"),
                            ("converted", "Converted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "pitched_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_targets",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("campaign", "customer")},
            },
        ),
    ]
